version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: animal-adoption-backend
    networks:
      - animal-adoption-api

networks:
  animal-adoption-api: